SchoolStoreApp/urls.py
from . import views
from django.urls import path

app_name='SchoolStoreApp'

urlpatterns = [

    path('',views.index,name='index'),
    path('formnewpage',views.formnewpage,name='formnewpage'),
    path('register',views.register,name='register'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('department',views.AllDepartment,name='AllDepartment'),
    path('<slug:dep_slug>/',views.AllDepartment,name='AllDepartments'),
    path('load-courses', views.load_courses, name='ajax_load_courses'),
    path('submitform',views.submitform,name='submitform'),
    path('stud_add',views.stud_add,name='stud_add'),

]

SchoolStoreProject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('SchoolStoreApp.urls'))
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

SchoolStoreApp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Department(models.Model):
    dep_name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    dep_description=models.TextField(blank=True)

    class Meta:
        ordering=('dep_name',)
        verbose_name='department'
        verbose_name_plural='departments'
    def get_url(self):
        return reverse('SchoolStoreApp:AllDepartments',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.dep_name)
class departmentcourse(models.Model):
    dep_name=models.ForeignKey(Department,on_delete=models.CASCADE)
    course=models.CharField(max_length=250,unique=True)
    def __str__(self):
        return '{}'.format(self.course)

class StudDetails(models.Model):
    stud_name=models.CharField(max_length=100)
    stud_dob=models.DateField()
    stud_age=models.IntegerField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ('O','Other')
    )
    stud_gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    stud_phno=models.CharField(max_length=10,unique=True)
    stud_email=models.EmailField(unique=True)
    stud_address=models.CharField(max_length=250)
    dep_name=models.ForeignKey(Department,on_delete=models.SET_NULL,null=True)
    course=models.ForeignKey(departmentcourse,on_delete=models.SET_NULL,null=True)
    Purposes = (
        ('E', 'Enquiry'),
        ('P', 'Place Order'),
        ('R', 'Return')
    )
    purpose = models.CharField(max_length=1, choices=Purposes)
    Notebook=models.BooleanField(default=False)
    Pen=models.BooleanField(default=False)
    Exam_Papers=models.BooleanField(default=False)
    def __str__(self):
        return '{}'.format(self.stud_name)

SchoolStoreApp/forms.py
from django import forms
from . models import StudDetails,departmentcourse
class StudForm(forms.ModelForm):
    class Meta:
        model=StudDetails
        fields="__all__"
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = departmentcourse.objects.none()
        if 'dep_name' in self.data:
            try:
                dep_name_id =int(self.data.get('dep_name'))
                self.fields['course'].queryset = departmentcourse.objects.filter(dep_name_id=dep_name_id).all()
            except (ValueError, TypeError):
                pass

SchoolStoreApp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .forms import StudForm
from . models import Department,departmentcourse

# Create your views here.
def formnewpage(request):
    return render(request,'newpage.html')
def index(request):
    return render(request,'index.html')

def register(request):
    if request.method=='POST':
        username = request.POST['user_name']
        pswd = request.POST['psw']
        pswrepeat = request.POST['psw-repeat']
        if pswd==pswrepeat:
            if User.objects.filter(username=username).exists():
                messages.info(request,"This Username already exists")
                return redirect(reverse('SchoolStoreApp:register'))
            else:
                user = User.objects.create_user(username=username,password=pswd)
                user.save();
                return redirect(reverse('SchoolStoreApp:login'))
        else:
            messages.info(request,"Password not matching")
            return redirect(reverse('SchoolStoreApp:register'))
            return redirect('/')
    return render(request, 'register.html')

def login(request):
    if request.method=='POST':
        username=request.POST['uname']
        password=request.POST['psw']
        user=auth.authenticate(username=username,password=password)
        if user is not None:
            auth.login(request,user)
            return redirect(reverse("SchoolStoreApp:formnewpage"))
        else:
            messages.info(request,"Invalid Username or Password")
            return redirect('/')
    return render(request,'Login.html')

def logout(request):
    auth.logout(request)
    return redirect('/')

def submitform(request):
    form=StudForm()
    if request.method=="POST":
        form=StudForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Request submitted successfully.')
            return redirect(reverse('SchoolStoreApp:submitform'))
    return render(request,'form.html',{'form': form})

def AllDepartment(request, dep_slug=None):
    dep_page=None
    departments=None
    if dep_slug!=None:
        dep_page=get_object_or_404(Department,slug=dep_slug)
        departments=Department.objects.all().filter(dep_name=dep_page)
    return render(request, "department.html", {'department':dep_page,'departments': departments})

def load_courses(request):
    dep_name_id = request.GET.get('dep_name_id')
    courses = departmentcourse.objects.filter(dep_name_id=dep_name_id).all()
    # print(list(courses.values('id', 'name')))
    return render(request, 'course_dropdown_list_options.html', {'courses': courses})

def stud_add(request):
    form1 = StudForm()
    if request.method == 'POST':
        form1 = StudForm(request.POST)
        if form1.is_valid():
            form1.save()
            messages.success(request, 'Request submitted successfully.')
            return redirect('stud_add')
    return render(request, 'form.html', {'form1': form1})

templates/Login.html
{% extends 'base.html' %}
{% block body %}

<h2 style="text-align:center;">Login Form</h2>

<form style="border: 3px solid #1f5fd5;" action="login" method="post">
    {% csrf_token %}
{% for msg in messages %}
      <h6>{{msg}}</h6>
    {% endfor %}
  <div class="container">
    <label for="uname"><b>Username</b></label>
    <input style="width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;" type="text" placeholder="Enter Username" name="uname" required>

    <label for="psw"><b>Password</b></label>
    <input style="width: 100%;
  padding: 12px 20px;
  margin: 8px 0;
  display: inline-block;
  border: 1px solid #ccc;
  box-sizing: border-box;" type="password" placeholder="Enter Password" name="psw" required>

    <button style="background-color: #04AA6D;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;" type="submit">Login</button>

  </div>
    <div class="container" style="background-color:#f1f1f1">
    <a href="{% url 'SchoolStoreApp:register' %}">Register here....</a>
  </div>
</form>

{% endblock %}

templates/Navbar.html
<div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5">
            <a href="index.html" class="navbar-brand ml-lg-3">
                <h1 class="m-0 text-uppercase text-primary"><i class="fa fa-book-reader mr-3"></i>SCHOOL STORE</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
           <div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mx-auto py-0">
                    <a href="{% url 'SchoolStoreApp:index' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'SchoolStoreApp:login' %}"  class="nav-item nav-link">Login</a>
                    <a href="{% url 'SchoolStoreApp:register' %}" class="nav-item nav-link">Register</a>
                    <div class="nav-item dropdown {% if 'SchoolStoreApp' in request.path %} active {% endif %}">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Department</a>
<!--                        <div class="dropdown-menu m-0">-->
                            <ul class="dropdown-menu">
<!--                                <li><a class="dropdown-item" href="{% url 'SchoolStoreApp:AllDepartment' %}">All Departments</a></li>-->
                                {% for dept in links %}
                                <li><a class="dropdown-item" href="{{dept.get_url}}">{{dept.dep_name}}</a></li>
                                {% endfor %}

                            </ul>
<!--                            <a href="detail.html" class="dropdown-item">Computer Science</a>-->

                        </div>
                    </div>
<!--                    <a href="register.html" class="nav-item nav-link">Register</a>-->
                </div>
            <div>
                <a href="{% url 'SchoolStoreApp:login' %}" class="btn btn-primary py-2 px-4 d-none d-lg-block">Login</a>
            </div>
        </nav>
    </div>

templates/Topbar.html
<div class="container-fluid bg-dark">
        <div class="row py-2 px-lg-5">
            <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center text-white">
                    <small><i class="fa fa-phone-alt mr-2"></i>+012 345 6789</small>
                    <small class="px-3">|</small>
                    <small><i class="fa fa-envelope mr-2"></i>info@schoolstore.com</small>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Online School Store</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
<!-- Topbar Start -->
 <div class="container-fluid bg-dark">
        <div class="row py-2 px-lg-5">
            <div class="col-lg-6 text-center text-lg-left mb-2 mb-lg-0">
                <div class="d-inline-flex align-items-center text-white">
                    <small><i class="fa fa-phone-alt mr-2"></i>+012 345 6789</small>
                    <small class="px-3">|</small>
                    <small><i class="fa fa-envelope mr-2"></i>info@schoolstore.com</small>
                </div>
            </div>
            <div class="col-lg-6 text-center text-lg-right">
                <div class="d-inline-flex align-items-center">
                    <a class="text-white px-2" href="">
                        <i class="fab fa-facebook-f"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-linkedin-in"></i>
                    </a>
                    <a class="text-white px-2" href="">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a class="text-white pl-2" href="">
                        <i class="fab fa-youtube"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <!-- Topbar End -->


    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5">
            <a href="index.html" class="navbar-brand ml-lg-3">
                <h1 class="m-0 text-uppercase text-primary"><i class="fa fa-book-reader mr-3"></i>SCHOOL STORE</h1>
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
           <div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mx-auto py-0">
                    <a href="{% url 'SchoolStoreApp:index' %}" class="nav-item nav-link active">Home</a>
                    <a href="{% url 'SchoolStoreApp:login' %}"  class="nav-item nav-link">Login</a>
                    <a href="{% url 'SchoolStoreApp:register' %}" class="nav-item nav-link">Register</a>
<!--                    <div class="nav-item dropdown {% if 'SchoolStoreApp' in request.path %} active {% endif %}">-->
<!--                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Department</a>-->
<!--&lt;!&ndash;                        <div class="dropdown-menu m-0">&ndash;&gt;-->
<!--                            <ul class="dropdown-menu">-->
<!--&lt;!&ndash;                                <li><a class="dropdown-item" href="{% url 'SchoolStoreApp:AllDepartment' %}">All Departments</a></li>&ndash;&gt;-->
<!--                                {% for dept in links %}-->
<!--                                <li><a class="dropdown-item" href="{{dept.get_url}}">{{dept.dep_name}}</a></li>-->
<!--                                {% endfor %}-->

<!--                            </ul>-->
<!--&lt;!&ndash;                            <a href="detail.html" class="dropdown-item">Computer Science</a>&ndash;&gt;-->

<!--                        </div>-->
                    </div>
<!--                    <a href="register.html" class="nav-item nav-link">Register</a>-->
                </div>
            <div>
                <a href="{% url 'SchoolStoreApp:login' %}" class="btn btn-primary py-2 px-4 d-none d-lg-block">Login</a>
            </div>
        </nav>
    </div>
{% block body %}
{% endblock %}
</body>
</html>

templates/course_dropdown_list_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.course }}</option>
{% endfor %}

templates/department.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    {% if department %}
    <h2><mark>{{department.dep_name}}</mark></h2><br>

     <h4>{{department.dep_description}}</h4>
    {% endif %}
</div>

{% endblock %}

templates/form.html
{% extends 'base.html' %}
{% block body %}

<!--<div>{% if user.is_authenticated %}-->
<!--    <h4 style="text-align:center;font-color:blue;">Welcome {{user.username}}</h4>-->
<!--    {% endif %}-->
<!--</div>-->

<form method="POST" id="StudForm"  data-courses-url="{% url 'SchoolStoreApp:ajax_load_courses' %}" >
    {% csrf_token %}
    {% include 'messages.html' %}
    {{ form.as_p }}
<!--    {% for fields in form %}-->
<!--    <label class="form_label" >{{fields.label}}</label>-->
<!--    {{fields}}-->
<!--    <br>-->
<!--    {% endfor %}-->
    <input type="submit" value="submit" class="btn btn-primary">

{% if user.is_authenticated %}
    <a href="{% url 'SchoolStoreApp:logout' %}" class="btn btn-primary">Logout</a>
{% endif %}

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_dep_name").change(function () {
        var url = $("#StudForm").attr("data-courses-url");
        const dep_nameId = $(this).val();
        $.ajax({
            url: url,
            data: {
                'dep_name_id': dep_nameId
            },
            success: function (data) {
                console.log(data)
                $("#id_course").html(data);

            }
        });

    });
</script>
{% endblock %}
<!--    {% csrf_token %}-->
<!--    <label> Name: </label>-->
<!--<input type="text" name="name" size="15"/> <br> <br>-->
<!--<label> DOB: </label>-->
<!--<input type="date" name="dob" size="15"/> <br> <br>-->
<!--<label> Age: </label>-->
<!--<input type="text" name="age" size="15"/> <br> <br>-->
<!-- <label>-->
<!--Gender :-->
<!--</label>-->
<!--<input type="radio" name="gender"/> Male-->
<!--<input type="radio" name="gender"/> Female-->
<!--<input type="radio" name="gender"/> Other-->
<!--<br>-->
<!--<br>-->
<!--<label>-->
<!--Phone Number:-->
<!--</label>-->
<!--<input type="text" name="phone" size="12"> <br> <br>-->
<!--<label>Email:</label>-->
<!--<input type="email" id="email" name="email"> <br>-->
<!--<br> <br>-->
<!--<label>Address:</label><br>-->
<!--<textarea cols="80" rows="5" value="address">-->
<!--</textarea>-->
<!--<br> <br>-->
<!--<label>-->
<!--Department :-->
<!--</label>-->
<!--<select>-->
<!--<option value="Department">Department</option>-->
<!--<option value="computer-science">computer Science</option>-->
<!--<option value="commerce">commerce</option>-->
<!--<option value="Bio-Science">Bio-Science</option>-->
<!--<option value="Humanities">Humanities</option>-->
<!--<option value="Aggriculture">Aggriculture</option>-->

<!--</select>-->
<!--<br>-->
<!--<br>-->
<!--<label>-->
<!--Course :-->
<!--</label>-->
<!--<select>-->
<!--<option value="Course">Course</option>-->
<!--<option value="BCA">BCA</option>-->
<!--<option value="BBA">BBA</option>-->
<!--<option value="B.Tech">B.Tech</option>-->
<!--<option value="MBA">MBA</option>-->
<!--<option value="MCA">MCA</option>-->
<!--<option value="M.Tech">M.Tech</option>-->
<!--</select>-->
<!--<br>-->
<!--<br>-->
<!--<label>-->
<!--Purpose :-->
<!--</label>-->
<!--<select>-->
<!--<option value="enquiry">Enquiry</option>-->
<!--<option value="placeorder">Place Order</option>-->
<!--<option value="return">Return</option>-->
<!--</select>-->
<!--<br>-->
<!--<br>-->
<!--<label>-->
<!--Materials Provide:-->
<!--</label><br>-->
<!--<input type="checkbox" name="notebook"> Notebook <br>-->
<!--<input type="checkbox" name="pen"> Pen <br>-->
<!--<input type="checkbox" name="exampapers"> Exam Papers  <br>-->
<!--<br>-->
<!--<br>-->
<!--<input type="submit" value="Submit">-->

templates/messages.html
{% if messages %}
  {% for message1 in messages %}
    <div class="alert alert-dismissible alert-success" >
      <button type="button" class="close" data-dismiss="alert">
        ×
      </button>
      <strong>{{message1}}</strong>
      <h6><a href="{% url 'SchoolStoreApp:index' %}">Home</a></h6>
    </div>

 {% endfor %}
{% endif %}

templates/newpage.html
{% extends 'base.html' %}
{% block body %}
<div>
    <a style="text-align:center;" href="{% url 'SchoolStoreApp:submitform' %}" class="btn btn-primary py-2 px-4 d-none d-lg-block">Form</a>
</div>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% block body %}
<form action="register" method="POST">
  {% csrf_token %}
  <div class="container">
    <h1>Register</h1>
    <p>Please fill in this form to create an account.</p>
    {% for msg in messages %}
      <h6>{{msg}}</h6>
    {% endfor %}
    <hr>

    <label for="user_name"><b>UserName</b></label>
    <input style="width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;" type="text"  name="user_name" id="user_name" placeholder="Enter username" required>

    <label for="psw"><b>Password</b></label>
    <input style="width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;" type="password"  name="psw" id="psw" placeholder="Enter Password" required>

    <label for="psw-repeat"><b>Repeat Password</b></label>
    <input style="width: 100%;
  padding: 15px;
  margin: 5px 0 22px 0;
  display: inline-block;
  border: none;
  background: #f1f1f1;" type="password" name="psw-repeat" id="psw-repeat" placeholder="Enter Confirm-Password" required>
    <hr>
    <button style="background-color: #04AA6D;
  color: white;
  padding: 16px 20px;
  margin: 8px 0;
  border: none;
  cursor: pointer;
  width: 100%;
  opacity: 0.9;" type="submit" class="registerbtn" >Submit</button>
  </div>

</form>

{% endblock %}